
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LapProject.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ProductsOfTheMonthView
{

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public string ManufacturerName { get; set; }

    public string CategoryName { get; set; }

    public decimal TaxRate { get; set; }

    public Nullable<int> TotalAmountSold { get; set; }

}

}
