
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LapProject.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Top5
{

    public string Name { get; set; }

    public Nullable<int> Anzahl { get; set; }

}

}
