
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LapProject.Data
{

using System;
    using System.Collections.Generic;
    
public partial class VerkaufteProdukteProMonatJeProdukt
{

    public Nullable<int> Year { get; set; }

    public Nullable<int> Month { get; set; }

    public string ProductName { get; set; }

    public Nullable<int> TotalSold { get; set; }

}

}
